### PR TITLE
remove .java files

### PR DESCRIPTION
**Pull request by rvkvld**
Want to merge! ?

### CODE REVIEW

**Comment by Jonesss** [comment]
"Want to merge!?" does not work.
When you are submitting your merged, the description of merge should contain full description of what you have changed.

**Comment by Jonesss** [comment]
If you take a look at "Files changed", you will see that you are not adding any new files, but deleting them. I do not see any your new work. Try to figure out why.

**Comment by rvkvld** [comment]
I got it. Ok I will add new junit tests and then do PR agin. What to do now? I mean with this existing PR?

**Comment by rvkvld** [comment]
cancel pull request

**Pull request closed without merging**
